store:
  availabilities:
    - German
    - International
  default_locale: en_GB
  localizations:
    - de_DE
    - en_GB
  categories:
    - Sonderfunktionen
  type: extension
  icon: src/Resources/config/plugin.png
  automatic_bugfix_version_compatibility: false
  description:
    de: file:src/Resources/store/de.md
    en: file:src/Resources/store/en.md
  tags:
    de:
      - spam
      - sicherheit
    en:
      - spam
      - security
  features:
    de:
      - self-hosted
      - Keine persönlichen Daten
      - Kein Tracking
      - accessibility
      - compliance
    en:
      - self-hosted
      - No personal data collection
      - No tracking
      - compliance
      - accessibility
  images:
    - file: src/Resources/store/images/0.jpg
      activate:
        de: true
        en: true
      preview:
        de: true
        en: true
      priority: 0
    - file: src/Resources/store/images/1.jpg
      activate:
        de: true
        en: true
      preview:
        de: false
        en: false
      priority: 1
    - file: src/Resources/store/images/2.jpg
      activate:
        de: true
        en: true
      preview:
        de: false
        en: false
      priority: 2
build:
  zip:
    assets:
      enable_es_build_for_admin: true
      enable_es_build_for_storefront: true
